// AUTO-GENERATED (auto-discovery breadth expansion, Jun 16 2026) by /tmp/taskscan.swift + the
// prompt-authoring workflow. 23 new reimplement-against-tests tasks (forward passes + algorithmic
// fns); 17 carry leak-stripped prompts (moderate/hard), 6 trivial are inactive. Do NOT hand-edit.
import Foundation

extension DomainEvalSuite {
    /// Auto-discovered tasks beyond the original 9 hand-inventoried backward passes (breadth).
    public static let autoTasks: [DomainTask] = [
        DomainTask(
            id: "Matrix.matmulNaive", repo: llmFromScratch,
            targetFileRel: "Sources/MiniLLM/Core/Matrix.swift",
            bodyStartLine: 229, bodyEndLine: 240,
            coveringTests: ["MatrixTests/testMatmulMatchesNaive", "MatrixTests/testMatmulSmallByHand"],
            siblingTests: [],
            docCommentLeaksFormula: true, bodyHash: "a2ed9a7fe8ff32bd",
            distinctiveSubstrings: [
                "for j in 0..<n { out[cBase + j] += a * other.data[bBase + j] }",
                "precondition(cols == other.rows, \"matmul shape mismatch\")",
                "var out = [Float](repeating: 0, count: m * n)",
            ],
            prompt: DomainPrompts.matrixMatmulNaive),
        DomainTask(
            id: "Matrix.transposed", repo: llmFromScratch,
            targetFileRel: "Sources/MiniLLM/Core/Matrix.swift",
            bodyStartLine: 190, bodyEndLine: 194,
            coveringTests: ["MatrixTests/testTranspose"],
            siblingTests: [],
            docCommentLeaksFormula: false, bodyHash: "2b55f1a15372191b",
            distinctiveSubstrings: [
                "for c in 0..<cols { out[c * rows + r] = data[r * cols + c] }",
                "return Matrix(rows: cols, cols: rows, data: out)",
                "var out = [Float](repeating: 0, count: count)",
            ],
            prompt: DomainPrompts.matrixTransposed),
        DomainTask(
            id: "Matrix.softmaxRows", repo: llmFromScratch,
            targetFileRel: "Sources/MiniLLM/Core/Matrix.swift",
            bodyStartLine: 133, bodyEndLine: 147,
            coveringTests: ["MatrixTests/testSoftmaxRowsSumToOne"],
            siblingTests: [],
            docCommentLeaksFormula: true, bodyHash: "b2dc4af1b1698bdc",
            distinctiveSubstrings: [
                "for c in 0..<cols { maxV = max(maxV, data[base + c]) }",
                "return Matrix(rows: rows, cols: cols, data: out)",
                "let e = Foundation.exp(data[base + c] - maxV)",
            ]),
            // DEACTIVATED (no prompt): mutation-sanity FAILED — a stub body still passes
            // testSoftmaxRowsSumToOne, so the test doesn't constrain the fn (it'd mint false-positive
            // traces). Re-add a prompt only with a stronger covering test (exact values, not sum-to-one).
        DomainTask(
            id: "Matrix.softmaxRowsBackward", repo: llmFromScratch,
            targetFileRel: "Sources/MiniLLM/Core/Matrix.swift",
            bodyStartLine: 160, bodyEndLine: 168,
            coveringTests: ["AttentionTests/testSoftmaxBackward"],
            siblingTests: [],
            docCommentLeaksFormula: true, bodyHash: "746e3cdc866d6c10",
            distinctiveSubstrings: [
                "for i in 0..<cols { out[base + i] = data[base + i] * (dA.data[base + i] - dot) }",
                "precondition(shape == dA.shape, \"shape mismatch in softmaxRowsBackward\")",
                "for j in 0..<cols { dot += data[base + j] * dA.data[base + j] }",
            ],
            prompt: DomainPrompts.matrixSoftmaxRowsBackward),
        DomainTask(
            id: "Matrix.colSums", repo: llmFromScratch,
            targetFileRel: "Sources/MiniLLM/Core/Matrix.swift",
            bodyStartLine: 120, bodyEndLine: 125,
            coveringTests: ["MatrixTests/testColSums"],
            siblingTests: [],
            docCommentLeaksFormula: true, bodyHash: "2a0d9047d2ba7722",
            distinctiveSubstrings: [
                "for c in 0..<cols { out[c] += data[base + c] }",
                "return Matrix(rows: 1, cols: cols, data: out)",
                "var out = [Float](repeating: 0, count: cols)",
            ]),
        DomainTask(
            id: "Matrix.addRowVector", repo: llmFromScratch,
            targetFileRel: "Sources/MiniLLM/Core/Matrix.swift",
            bodyStartLine: 176, bodyEndLine: 182,
            coveringTests: ["MatrixTests/testAddRowVectorBroadcasts"],
            siblingTests: [],
            docCommentLeaksFormula: true, bodyHash: "246bc5cb786c2b24",
            distinctiveSubstrings: [
                "precondition(v.rows == 1 && v.cols == cols, \"row vector must be 1×\\(cols)\")",
                "for c in 0..<cols { out[base + c] += v.data[c] }",
                "return Matrix(rows: rows, cols: cols, data: out)",
            ]),
        DomainTask(
            id: "Linear.forward", repo: llmFromScratch,
            targetFileRel: "Sources/MiniLLM/Layers/Linear.swift",
            bodyStartLine: 56, bodyEndLine: 57,
            coveringTests: ["LinearTests/testLinearForwardShape", "LinearTests/testLinearGradients"],
            siblingTests: [],
            docCommentLeaksFormula: true, bodyHash: "96a89ec3032cd204",
            distinctiveSubstrings: [
                "self.x = x                                   // remember input for backward",
                "return x.matmul(W.value).addRowVector(b.value)",
            ]),
        DomainTask(
            id: "GELU.forward", repo: llmFromScratch,
            targetFileRel: "Sources/MiniLLM/Layers/GELU.swift",
            bodyStartLine: 34, bodyEndLine: 38,
            coveringTests: ["LayersTests/testGELUKnownValues", "LayersTests/testGELUGradient"],
            siblingTests: [],
            docCommentLeaksFormula: true, bodyHash: "7b66fbcc275d460d",
            distinctiveSubstrings: [
                "let inner = GELU.c * (v + GELU.a * v * v * v)",
                "return 0.5 * v * (1 + Foundation.tanh(inner))",
                "return x.map { v in",
            ],
            prompt: DomainPrompts.gELUForward),
        DomainTask(
            id: "LayerNorm.forward", repo: llmFromScratch,
            targetFileRel: "Sources/MiniLLM/Layers/LayerNorm.swift",
            bodyStartLine: 54, bodyEndLine: 80,
            coveringTests: ["LayersTests/testLayerNormNormalizes", "LayersTests/testLayerNormGradients"],
            siblingTests: [],
            docCommentLeaksFormula: false, bodyHash: "769e3ff8e5c6148f",
            distinctiveSubstrings: [
                "for c in 0..<d { let dv = x.data[base + c] - mean; varSum += dv * dv }",
                "out[base + c] = h * gamma.value.data[c] + beta.value.data[c]",
                "let istd = 1 / Foundation.sqrt(variance + eps)",
            ],
            prompt: DomainPrompts.layerNormForward),
        DomainTask(
            id: "SoftmaxCrossEntropy.forward", repo: llmFromScratch,
            targetFileRel: "Sources/MiniLLM/Layers/SoftmaxCrossEntropy.swift",
            bodyStartLine: 49, bodyEndLine: 63,
            coveringTests: ["LayersTests/testCrossEntropyUniformEqualsLogVocab", "LayersTests/testCrossEntropyGradient"],
            siblingTests: [],
            docCommentLeaksFormula: false, bodyHash: "26877d4395a00b07",
            distinctiveSubstrings: [
                "activeCount = max(active, 1)                  // guard against an all-masked batch",
                "precondition(logits.rows == targets.count, \"need one target per row\")",
                "loss += -Foundation.log(max(pt, 1e-12))   // clamp guards log(0)",
            ],
            prompt: DomainPrompts.softmaxCrossEntropyForward),
        DomainTask(
            id: "Embedding.forward", repo: llmFromScratch,
            targetFileRel: "Sources/MiniLLM/Layers/Embedding.swift",
            bodyStartLine: 44, bodyEndLine: 51,
            coveringTests: ["LayersTests/testEmbeddingForwardGathersRows", "LayersTests/testEmbeddingGradient"],
            siblingTests: [],
            docCommentLeaksFormula: false, bodyHash: "5eb3ffb20a65059b",
            distinctiveSubstrings: [
                "for c in 0..<dModel { out[dst + c] = weight.value.data[src + c] }",
                "var out = [Float](repeating: 0, count: ids.count * dModel)",
                "return Matrix(rows: ids.count, cols: dModel, data: out)",
            ]),
        DomainTask(
            id: "MultiHeadSelfAttention.forward", repo: llmFromScratch,
            targetFileRel: "Sources/MiniLLM/Attention/MultiHeadSelfAttention.swift",
            bodyStartLine: 64, bodyEndLine: 88,
            coveringTests: ["AttentionTests/testAttentionForwardShape", "AttentionTests/testAttentionGradients"],
            siblingTests: [],
            docCommentLeaksFormula: false, bodyHash: "adc1b35a4348f64b",
            distinctiveSubstrings: [
                "headQ.append(q); headK.append(k); headV.append(v); headA.append(a)",
                "applyCausalMask(&scores)                       //         step 3",
                "let a = scores.softmaxRows()                   // (T×T)  step 4",
            ],
            prompt: DomainPrompts.multiHeadSelfAttentionForward),
        DomainTask(
            id: "AdamW.step", repo: llmFromScratch,
            targetFileRel: "Sources/MiniLLM/Training/AdamW.swift",
            bodyStartLine: 59, bodyEndLine: 77,
            coveringTests: ["TrainingTests/testAdamWConvergesToMinimum", "TrainingTests/testWeightDecayShrinksMatricesNotVectors"],
            siblingTests: [],
            docCommentLeaksFormula: false, bodyHash: "d54388bc6dedd3e4",
            distinctiveSubstrings: [
                "let update = mHat / (vHat.squareRoot() + eps) + decay * p.value.data[j]",
                "let bc1 = 1 - Float(pow(Double(beta1), Double(t)))   // 1 − β₁ᵗ",
                "let bc2 = 1 - Float(pow(Double(beta2), Double(t)))   // 1 − β₂ᵗ",
            ],
            prompt: DomainPrompts.adamWStep),
        DomainTask(
            id: "BPE.countPairs", repo: llmFromScratch,
            targetFileRel: "Sources/MiniLLM/Tokenizer/BPETokenizer.swift",
            bodyStartLine: 59, bodyEndLine: 64,
            coveringTests: ["BPETokenizerTests/testCountPairs"],
            siblingTests: [],
            docCommentLeaksFormula: false, bodyHash: "0b253f303231e39a",
            distinctiveSubstrings: [
                "counts[TokenPair(ids[i], ids[i + 1]), default: 0] += 1",
                "guard ids.count >= 2 else { return counts }",
                "var counts: [TokenPair: Int] = [:]",
            ]),
        DomainTask(
            id: "BPE.merge", repo: llmFromScratch,
            targetFileRel: "Sources/MiniLLM/Tokenizer/BPETokenizer.swift",
            bodyStartLine: 75, bodyEndLine: 87,
            coveringTests: ["BPETokenizerTests/testMergeReplacesEveryOccurrence"],
            siblingTests: [],
            docCommentLeaksFormula: false, bodyHash: "81675a2630c9cc78",
            distinctiveSubstrings: [
                "if i + 1 < ids.count, ids[i] == pair.a, ids[i + 1] == pair.b {",
                "out.reserveCapacity(ids.count)",
                "while i < ids.count {",
            ],
            prompt: DomainPrompts.bPEMerge),
        DomainTask(
            id: "BPE.encode", repo: llmFromScratch,
            targetFileRel: "Sources/MiniLLM/Tokenizer/BPETokenizer.swift",
            bodyStartLine: 175, bodyEndLine: 190,
            coveringTests: ["BPETokenizerTests/testRoundTripExact", "BPETokenizerTests/testCompresses"],
            siblingTests: [],
            docCommentLeaksFormula: false, bodyHash: "825d7c2b812c1586",
            distinctiveSubstrings: [
                "if let rank = merges[pair], rank < bestRank {",
                "var ids = Array(text.utf8).map { Int($0) }",
                "ids = merge(ids, pair, merges[pair]!)",
            ],
            prompt: DomainPrompts.bPEEncode),
        DomainTask(
            id: "Sampler.sampleToken", repo: llmFromScratch,
            targetFileRel: "Sources/MiniLLM/Sampling/Sampler.swift",
            bodyStartLine: 51, bodyEndLine: 84,
            coveringTests: ["SamplingTests/testGreedyPicksArgmax", "SamplingTests/testTopK1IsGreedy", "SamplingTests/testTopKRestrictsSupport", "SamplingTests/testTopPDropsTail"],
            siblingTests: [],
            docCommentLeaksFormula: false, bodyHash: "59c024993f2a65ad",
            distinctiveSubstrings: [
                "let order = (0..<n).sorted { probs[$0] > probs[$1] }   // most → least likely",
                "for i in 0..<n where scaled[i] < kthLargest { scaled[i] = -.infinity }",
                "if total > 0 { for i in 0..<n { probs[i] /= total } }   // renormalize",
            ],
            prompt: DomainPrompts.samplerSampleToken),
        DomainTask(
            id: "Sampler.sampleCategorical", repo: llmFromScratch,
            targetFileRel: "Sources/MiniLLM/Sampling/Sampler.swift",
            bodyStartLine: 106, bodyEndLine: 112,
            coveringTests: ["SamplingTests/testEmpiricalMatchesSoftmax"],
            siblingTests: [],
            docCommentLeaksFormula: false, bodyHash: "aca4df40a31548e0",
            distinctiveSubstrings: [
                "return probs.count - 1   // float roundoff fallback",
                "let u = Float.random(in: 0 ..< 1, using: &rng)",
                "for (i, p) in probs.enumerated() {",
            ],
            prompt: DomainPrompts.samplerSampleCategorical),
        DomainTask(
            id: "TokenDataset.sampleBatch", repo: llmFromScratch,
            targetFileRel: "Sources/MiniLLM/Training/TokenDataset.swift",
            bodyStartLine: 25, bodyEndLine: 35,
            coveringTests: ["TrainingTests/testTokenDatasetWindows"],
            siblingTests: [],
            docCommentLeaksFormula: false, bodyHash: "e05cbc924d0d0866",
            distinctiveSubstrings: [
                "precondition(ids.count >= blockSize + 1, \"corpus too short for this blockSize\")",
                "let target = Array(ids[start + 1 ..< start + blockSize + 1])",
                "let start = Int.random(in: 0...lastStart, using: &rng)",
            ],
            prompt: DomainPrompts.tokenDatasetSampleBatch),
        DomainTask(
            id: "Instruct.tokenize", repo: llmFromScratch,
            targetFileRel: "Sources/MiniLLM/Training/Instruct.swift",
            bodyStartLine: 38, bodyEndLine: 52,
            coveringTests: ["InstructTests/testInstructionTokenizeMasksPrompt"],
            siblingTests: [],
            docCommentLeaksFormula: false, bodyHash: "88d581654898c446",
            distinctiveSubstrings: [
                "for i in 0..<target.count where (i + 1) < promptIds.count {",
                "let responseIds = tok.encode(ex.response)",
                "let promptIds = tok.encode(ex.prompt)",
            ],
            prompt: DomainPrompts.instructTokenize),
        DomainTask(
            id: "MLP.forward", repo: llmFromScratch,
            targetFileRel: "Sources/MiniLLM/Layers/MLP.swift",
            bodyStartLine: 29, bodyEndLine: 29,
            coveringTests: ["TransformerTests/testMLPGradients"],
            siblingTests: [],
            docCommentLeaksFormula: false, bodyHash: "2d2ae1aec94798d2",
            distinctiveSubstrings: [
                "proj.forward(act.forward(fc.forward(x)))",
            ]),
        DomainTask(
            id: "TransformerBlock.forward", repo: llmFromScratch,
            targetFileRel: "Sources/MiniLLM/Transformer/TransformerBlock.swift",
            bodyStartLine: 46, bodyEndLine: 48,
            coveringTests: ["TransformerTests/testTransformerBlockGradients"],
            siblingTests: [],
            docCommentLeaksFormula: false, bodyHash: "7872bb1136c746cb",
            distinctiveSubstrings: [
                "let a = x + attn.forward(ln1.forward(x))     // residual 1",
                "let y = a + mlp.forward(ln2.forward(a))      // residual 2",
            ],
            prompt: DomainPrompts.transformerBlockForward),
        DomainTask(
            id: "GPT.forward", repo: llmFromScratch,
            targetFileRel: "Sources/MiniLLM/Transformer/GPT.swift",
            bodyStartLine: 81, bodyEndLine: 90,
            coveringTests: ["TransformerTests/testGPTForwardShape", "TransformerTests/testGPTGradients"],
            siblingTests: [],
            docCommentLeaksFormula: false, bodyHash: "dab3b124adde25a1",
            distinctiveSubstrings: [
                "let te = tokEmb.forward(ids)                 // (T × C)  token meaning",
                "precondition(T <= config.blockSize, \"sequence longer than blockSize\")",
                "let pe = posEmb.forward(Array(0..<T))        // (T × C)  position",
            ],
            prompt: DomainPrompts.gPTForward),
    ]
}
