// AUTO-GENERATED by the compile-validated prompt-authoring workflow (wf_e12f8cf6-71a).
// Each prompt was confirmed to compile a reference solution + leak-checked. Do NOT hand-edit.
import Foundation

enum DomainPrompts {
    static let geluBackward =
"""
Implement the BODY of this method (file Sources/MiniLLM/Layers/GELU.swift):

    public func backward(_ dOut: Matrix) -> Matrix

This is the backward (gradient) pass of a GELU activation layer. GELU has NO parameters, so backward only needs to compute and RETURN dL/d(input) — it does not touch any Parameter grads.

FORWARD (already implemented, given here only as context for what you are differentiating):
The layer's forward pass applies, elementwise to every entry v of the input matrix,
    gelu(v) = 0.5 · v · (1 + tanh(inner)),   where   inner = GELU.c · (v + GELU.a · v³)
GELU.c and GELU.a are the two static lets defined on the layer (GELU.c = √(2/π) ≈ the constant, GELU.a = 0.044715). Your backward must be the analytic derivative of THIS exact forward, applied elementwise, then chained against the upstream gradient.

State & shapes you may rely on:
- `self.x` is `Matrix?` — the input that was cached by forward. At the top of the body do `guard let x else { fatalError("GELU.backward called before forward") }` to unwrap it. After unwrapping, `x` is a `Matrix`.
- `dOut` (the parameter) is the upstream gradient dL/d(output), the SAME shape as `x`.
- The method must RETURN a `Matrix` (dL/d(input)), the same shape as `x` and `dOut`.
- GELU is purely elementwise: output entry i depends only on input entry i. So the per-element local derivative gelu'(v) forms a matrix the same shape as x, and dL/d(input) is the elementwise (Hadamard) product of `dOut` with that local-derivative matrix.

The EXACT API of the bespoke types (use these names precisely):
    struct Matrix {                       // value type (struct) — copies on assignment, copy-on-write
        var data: [Float]                 // row-major flat storage; readable AND writable (subscript-by-index)
        var count: Int                    // == rows * cols (total element count)
        var rows: Int                     // get-only
        var cols: Int                     // get-only
        func map(_ f: (Float) -> Float) -> Matrix   // elementwise map → new Matrix, same shape
        static func * (a: Matrix, b: Matrix) -> Matrix   // ELEMENTWISE (Hadamard) product; requires identical shapes
        static func * (a: Matrix, s: Float) -> Matrix    // scalar scaling
        static func + (a: Matrix, b: Matrix) -> Matrix   // elementwise add
        static func - (a: Matrix, b: Matrix) -> Matrix   // elementwise subtract
    }
    final class GELU {                    // the enclosing type
        static let c: Float               // √(2/π)
        static let a: Float               // 0.044715
    }
On the layer, reference the constants as `GELU.c` and `GELU.a`.
From Foundation, you may call `Foundation.tanh(_:)` (takes/returns a Float here).

Suggested shape of the body (you fill in the local derivative):
    guard let x else { fatalError("GELU.backward called before forward") }
    var grad = x                          // a writable Matrix the same shape as x
    for i in 0..<x.count {
        let v = x.data[i]
        // ... compute the elementwise local derivative gelu'(v) and store it ...
        grad.data[i] = /* your expression */
    }
    return dOut * grad                    // chain rule: dL/dx = dL/dy ⊙ gelu'(x)
You may instead build `grad` via `x.map { ... }` if you prefer — both are fine.

Gotchas:
- `*` between two Matrix values is the ELEMENTWISE (Hadamard) product, NOT matmul. `dOut * grad` is exactly what the chain rule needs here.
- `count` is a PROPERTY (no parens). So are `rows`/`cols`.
- `Matrix` is a struct (value type): `var grad = x` gives you an independent, mutable copy; writing `grad.data[i] = ...` does not disturb the cached `x`.
- Index `data` directly (`x.data[i]`, `grad.data[i] = ...`) — there is no `+=` family being asked for here.
- The constants live on the type: write `GELU.c` and `GELU.a`, not bare `c`/`a`.

Requirements:
- RETURN the Matrix dL/d(input), the same shape as `x`/`dOut`.
- Compute the GELU derivative analytically (do not approximate numerically), elementwise, and chain it with `dOut`.
- Do not allocate Parameters or touch any `.grad` — GELU has none.

Respond with ONLY the Swift statements inside the function body — no signature, no braces, no code fences, no commentary.
"""

    static let embeddingBackward =
"""
Implement the BODY of this method in Sources/MiniLLM/Layers/Embedding.swift:

    /// Scatter the upstream gradient back into the rows we read.
    public func backward(_ dOut: Matrix)

This is the backward pass of an Embedding lookup table (token id -> learned vector). It conforms to NO `Layer` protocol: its input is a list of integer ids, and integers are not differentiable, so there is NO dL/dInput to return. This method returns VOID — do NOT return anything. Its only job is to accumulate gradient into the table's parameter.

State & shapes you may rely on (all are members of the enclosing `Embedding` class, already in scope):
    - `weight: Parameter`     — the embedding table, value is a Matrix of shape (vocabSize x dModel), stored row-major.
    - `dModel: Int`           — width of each embedding row (the column count of the table).
    - `vocabSize: Int`        — number of rows in the table.
    - `self.ids: [Int]?`      — the token ids passed to the most recent `forward(_:)` call, cached for this scatter. Length N. Each entry is a row index into the table in 0..<vocabSize, and a token may repeat within the list.
    - `dOut: Matrix`          — the upstream gradient dL/d(output), shape (N x dModel), same shape `forward` returned. Row i of `dOut` corresponds to ids[i].

Recall what `forward` did: for each position i it COPIED table row `ids[i]` into output row i. So the gradient flows straight back to the table row that was read. Because `ids` may contain the same token more than once, a single table row can receive contributions from multiple positions, and those contributions must ACCUMULATE (add on top of whatever is already there) — never overwrite. `weight.grad` is pre-zeroed by the caller (the test calls `zeroGrad()` first), so you only need to add.

The EXACT API of the bespoke types (use these names precisely — do NOT invent members):
    final class Parameter {
        var value: Matrix     // the table's values, shape (vocabSize x dModel)
        var grad: Matrix      // dL/d(value), SAME shape as value; this is what you accumulate into
    }
    struct Matrix {
        var data: [Float]     // ROW-MAJOR flat storage; element (r, c) lives at index r*cols + c. This is a mutable [Float] you may index and assign element-by-element.
        var count: Int        // rows*cols
        var rows: Int { get }
        var cols: Int { get }
        subscript(_ r: Int, _ c: Int) -> Float { get set }   // (r,c) accessor if you prefer it over raw data indexing
    }

Storage layout you will need: in a Matrix of width `dModel`, the row for index t begins at flat offset `t * dModel` in `.data`, and its columns occupy the next `dModel` slots. This holds for both `weight.grad.data` and `dOut.data`.

Gotchas:
    - Returns VOID. There is no dL/dInput — do not return a value, do not construct a result Matrix.
    - The first thing the body must do is unwrap `self.ids`; if it is nil, `forward` was never called — `fatalError("Embedding.backward called before forward")`.
    - Matrix has NO `+=` operator and the element-wise Matrix `+` operator requires identical shapes — `dOut` (N x dModel) and `weight.grad` (vocabSize x dModel) do NOT have the same shape, so you CANNOT do a whole-Matrix add. Work at the level of individual Float elements inside `.data` (Float `+=` is fine on array elements).
    - ACCUMULATE into `weight.grad.data` (add), do not assign/overwrite — repeated tokens depend on this.
    - `weight.grad` already has the correct (vocabSize x dModel) shape and is zeroed by the caller; do not reallocate it.
    - Iterate over the cached ids with their positions (e.g. `for (i, t) in ids.enumerated()`), where `i` indexes `dOut`'s rows and `t` is the destination row in the table.

Requirements:
    - Use only the API listed above. No new types, no helper functions, no autograd.
    - Match row-major indexing exactly (offset = rowIndex * dModel + column).

Respond with ONLY the Swift statements inside the function body — no signature, no braces, no fences, no commentary.
"""

    static let mlpBackward =
"""
Implement the BODY of this method in Sources/MiniLLM/Layers/MLP.swift:

    public func backward(_ dOut: Matrix) -> Matrix

Context — what MLP is:
MLP is the transformer block's feed-forward network. It owns three sub-layers and runs them in this exact FORWARD order (read straight from MLP.forward):

    public func forward(_ x: Matrix) -> Matrix {
        proj.forward(act.forward(fc.forward(x)))
    }

i.e. the data flows  x → fc → act → proj → output. Concretely:
    • `fc`   : a `Linear` layer            (dModel → hidden)
    • `act`  : a `GELU` activation layer   (private let act = GELU())
    • `proj` : a `Linear` layer            (hidden → dModel)

State & shapes you may rely on:
    • `dOut` is dL/d(output), a Matrix the SAME shape as MLP's forward output (N × dModel).
    • Each sub-layer already cached whatever it needs during its own forward pass; you do NOT touch any caches here.
    • This method must RETURN dL/d(input) — a Matrix the same shape as MLP's original input x (N × dModel).
    • Each sub-layer's `backward` internally accumulates its own parameter gradients as a side effect; you do not manage those here. You only thread the gradient Matrix through the sub-layers.

The EXACT API of the bespoke types (use these names precisely):
    // Every sub-layer conforms to the `Layer` protocol:
    protocol Layer: AnyObject {
        func forward(_ x: Matrix) -> Matrix
        func backward(_ dOut: Matrix) -> Matrix   // takes dL/d(its output), returns dL/d(its input)
        var parameters: [Parameter] { get }
    }
    // MLP's stored sub-layers (these are the ONLY identifiers you need):
    let fc: Linear      // Linear: Layer
    let act: GELU       // GELU:   Layer   (the private `act` property)
    let proj: Linear    // Linear: Layer
    // So `fc.backward(m)`, `act.backward(m)`, and `proj.backward(m)` are each
    // `(Matrix) -> Matrix`, returning the gradient w.r.t. that sub-layer's input.
    struct Matrix { /* value type; you only need to pass it through, no methods required */ }

Gotchas:
    • This is purely COMPOSITIONAL — no math, no transposes, no matmul. You only call the three sub-layers' `backward` methods and feed each one's result into the next.
    • Order matters: a `backward` pass walks the sub-layers in the REVERSE of the forward order. Figure out that reverse order from the forward chain above and nest the calls so the gradient enters at the output end and exits at the input end.
    • Each `sublayer.backward(...)` consumes dL/d(that sub-layer's output) and produces dL/d(that sub-layer's input), which is exactly the upstream gradient for the PREVIOUS sub-layer in the forward chain.
    • Use the property names `fc`, `act`, `proj` exactly. `act` is the GELU instance.
    • The whole body is a single expression that returns a Matrix.

Requirements:
    • Start the chain by feeding `dOut` into the LAST sub-layer of the forward pass, then thread the result back through the remaining sub-layers in reverse, and RETURN the final Matrix.
    • Do not introduce new layers, allocate caches, or touch parameter grads directly.

Respond with ONLY the Swift statements inside the function body — no signature, no braces, no fences, no commentary.
"""

    static let softmaxCEBackward =
"""
Implement the BODY of this method in a hand-rolled Swift neural-net library (a NumPy-style `Matrix` of Float, row-major, no autograd — layers do their own backprop). This is the fused softmax + cross-entropy loss object; you are writing its `backward`, which returns the gradient of the scalar loss with respect to the logits that were passed to `forward`.

Signature (do NOT repeat it — implement only the body):

    public func backward() -> Matrix

This method returns a Matrix (the gradient dL/dlogits, same N×V shape as the logits) — it is NOT Void. The forward pass that ran before this stored everything you need on `self`.

State & shapes you may rely on (all are instance properties on `self`, already populated by a prior `forward(...)` call):
- `self.probs` : `Matrix?` — the row-wise softmax of the logits, shape N×V (N rows = positions/examples, V cols = vocabulary size). Each row is a probability distribution that sums to 1.
- `self.targets` : `[Int]?` — length N. `targets[r]` is the id (a column index in 0..<V) of the correct class for row r.
- `self.ignoreIndex` : `Int` — a sentinel. If `targets[r] == ignoreIndex`, row r was MASKED OUT of the loss in forward and must contribute exactly zero gradient (the whole row of the returned Matrix is zeros).
- `self.activeCount` : `Int` — the number of rows that actually contributed to the loss (i.e. rows whose target was not `ignoreIndex`); always >= 1. `forward` averaged the loss over these active rows, so your gradient must use the SAME normalizer to stay consistent with that mean.

`probs` and `targets` are Optionals; unwrap them first (e.g. `guard let probs, let targets else { fatalError(...) }`), exactly as the existing code does when called before forward.

The EXACT API of the bespoke types (use these names precisely — do not invent members):

    struct Matrix {
        var rows: Int            // get-only
        var cols: Int            // get-only
        var count: Int           // rows*cols, get-only
        var data: [Float]        // row-major storage; element (r,c) is at index r*cols + c. Mutable.
        subscript(_ r: Int, _ c: Int) -> Float   // get/set, same r*cols+c indexing
        init(rows: Int, cols: Int, data: [Float]) // precondition: data.count == rows*cols
        init(rows: Int, cols: Int)                // all-zeros
        func map(_ f: (Float) -> Float) -> Matrix
        var transposed: Matrix                    // PROPERTY, no parens
        func matmul(_ other: Matrix) -> Matrix    // true matrix product (BLAS)
        func colSums() -> Matrix                  // (1 × cols) row vector
        static func + (Matrix, Matrix) -> Matrix  // element-wise, shapes must match
        static func - (Matrix, Matrix) -> Matrix  // element-wise, shapes must match
        static func * (Matrix, Matrix) -> Matrix  // element-wise (Hadamard), shapes must match
        static func * (Matrix, Float) -> Matrix   // scalar scaling
        static func * (Float, Matrix) -> Matrix   // scalar scaling
    }

Gotchas:
- Matrix has NO `+=` / `-=` / `*=` operators. To build a result you can either mutate a local `[Float]` copy of `probs.data` element-by-element and wrap it back up with `Matrix(rows:cols:data:)`, or use the value-returning operators above; either is fine.
- `transposed` is a PROPERTY (no parentheses). `count`, `rows`, `cols` are also properties.
- `*` on two Matrices is ELEMENT-WISE (Hadamard), not matmul; the real matrix product is `matmul`. Element-wise `+ - *` require identical shapes and will `precondition`-trap otherwise.
- `data` is a flat row-major array: row r, column c lives at index `r * cols + c`. There is no 2-D buffer.
- Integer math: convert counts with `Float(...)` before dividing, or you will do integer division.
- The returned Matrix must be exactly N×V (same shape as the logits / as `probs`).

Requirements:
- Return the gradient of the mean cross-entropy loss with respect to the logits, as an N×V Matrix.
- A row whose target equals `ignoreIndex` must be entirely zero in the output.
- Normalize by the same active-row count that `forward` used to average the loss, so the analytic gradient matches a numerical finite-difference check.
- Use only the API listed above; do not call any softmax/cross-entropy helpers — the softmax output is already cached in `self.probs`.

Respond with ONLY the Swift statements that go inside the function body — no signature, no braces, no fences, no commentary.
"""

}